### ISSUE TITLE
Creating Bounties as Participants should NOT be allowed

### ISSUE THREAD

**Issue by ConnorGargano** [baileypumfleet/osshack#5]
A Participant is able to create a bounty by adjusting the URL with .../add.

Only companies should be able to access this page.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @ConnorGargano . I'm eager to contribute to the resolution and have a quick question.
Could you provide more details about the expected behavior? Does this pertain to the URL "https://osshack.com/dashboard/new"? Specifically, do you recommend checking the `projectId` before redirecting the user? I've assumed that this would be the case and would like to submit a pull request. If you'd like me to make any changes, please let me know.
Looking forward to your guidance.

**Comment by baileypumfleet** [comment]
Resolved
